databases:
  - name: vaultDatabase
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: the-vault
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn PasswordManager.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vaultDatabase
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4